name: 'wescrm deploy action'
description: 'wescrm部署action'
inputs:
  type:
    description: '类型：web'
    required: true
    default: 'message'
  
  app: 
    description: '项目名称'

  branch: 
    description: '项目分支名称'

  input: 
    description: '目录地址'

  # message
  content:
    description: '发送内容'

  # web
  host: 
    description: '服务器host'
  port: 
    description: '服务器port'
  username: 
    description: '服务器username'
  password: 
    description: '服务器password'
  output: 
    description: '服务器部署地址'


runs:
  using: 'node12'
  main: 'src/index.js'