name: 'wescrm deploy action'
description: 'wescrm部署action'
inputs:
  type:
    description: '类型：message,miniprogram,web'
    required: true
    default: 'message'

  # message
  content:
    description: '发送内容'

  # web
  host: 
    description: '服务器host'
  port: 
    description: '服务器port'
  username: 
    description: '服务器username'
  password: 
    description: '服务器password'
  input: 
    description: '目录地址'
  output: 
    description: '服务器部署地址'

  
runs:
  using: 'node12'
  main: 'src/index.js'